/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ylztclwqmfhczklsswrt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsenRjbHdxbWZoY3prbHNzd3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzAwMjgsImV4cCI6MjA4NTk0NjAyOH0.9K4fPLqd3THZvZdpN1AQZ-b4nFunJk2-0BcZea9SO0I"