import { useState, useEffect, useRef } from 'react';
import { Plus, X, Clock, ChevronDown, Check } from 'lucide-react';
import { useT } from '../hooks/useT';
import { tr, translations } from '../utils/translations';

interface ScheduleEntry {
  days: string[];
  from: string;
  to: string;
}

interface WorkingHoursSelectorProps {
  /** Serbian / Latin display text (DB opening_hours) */
  value_sr: string;
  /** English display text (DB opening_hours_en) */
  value_en: string;
  onChange: (opening_hours: string, opening_hours_en: string) => void;
}

const ALL_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

const TIME_OPTIONS: string[] = [];
for (let h = 0; h < 24; h++) {
  for (let m = 0; m < 60; m += 30) {
    TIME_OPTIONS.push(`${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}`);
  }
}
// 00:00 is already generated by the loop (h=0, m=0) — no duplicate needed

function getDayShortKey(day: string): string {
  const map: Record<string, string> = {
    monday: 'monShort', tuesday: 'tueShort', wednesday: 'wedShort',
    thursday: 'thuShort', friday: 'friShort', saturday: 'satShort', sunday: 'sunShort'
  };
  return map[day] || day;
}

/** Sort selected days Mon → Sun for grouping */
function sortDaysWeekOrder(days: string[]): string[] {
  return [...new Set(days)].sort((a, b) => ALL_DAYS.indexOf(a) - ALL_DAYS.indexOf(b));
}

/**
 * Format day selection: consecutive runs become Pon-Pet / Mon-Fri, Sat-Sun; non-consecutive as comma-separated singles or runs.
 */
function formatDayGroups(days: string[], t: (key: string) => string): string {
  const sorted = sortDaysWeekOrder(days);
  if (sorted.length === 0) return '';
  if (sorted.length === 7) return t('everyDay');

  const runs: string[][] = [];
  let runStart = 0;
  for (let i = 1; i <= sorted.length; i++) {
    const prevIdx = ALL_DAYS.indexOf(sorted[i - 1]);
    const atEnd = i === sorted.length;
    const consecutive =
      !atEnd && ALL_DAYS.indexOf(sorted[i]) === prevIdx + 1;
    if (atEnd || !consecutive) {
      runs.push(sorted.slice(runStart, i));
      runStart = i;
    }
  }

  return runs
    .map((run) => {
      if (run.length === 1) return t(getDayShortKey(run[0]));
      return `${t(getDayShortKey(run[0]))}-${t(getDayShortKey(run[run.length - 1]))}`;
    })
    .join(', ');
}

function serializeSchedule(entries: ScheduleEntry[], t: (key: string) => string): string {
  if (entries.length === 0) return '';
  return entries
    .map((entry) => `${formatDayGroups(entry.days, t)}: ${entry.from}-${entry.to}`)
    .join('; ');
}

/** Map short day labels (sr + en) → canonical day id */
function buildShortToDayMap(): Record<string, string> {
  const m: Record<string, string> = {};
  for (const day of ALL_DAYS) {
    const sk = getDayShortKey(day);
    m[tr(sk, 'sr').toLowerCase()] = day;
    m[tr(sk, 'en').toLowerCase()] = day;
  }
  return m;
}

const SHORT_TO_DAY = buildShortToDayMap();

const EVERY_DAY_LABELS_LOWER = new Set([
  tr('everyDay', 'sr').toLowerCase(),
  tr('everyDay', 'en').toLowerCase(),
]);

/**
 * Parse "Pon-Pet", "Mon-Fri", "Sub, Ned", "Pon-Pet, Sub-Ned", "Svaki dan" into canonical day ids.
 */
function parseDayLabelString(dayPartRaw: string): string[] | null {
  const dayPart = dayPartRaw.replace(/[\u2013\u2014]/g, '-').trim();
  if (!dayPart) return null;

  if (EVERY_DAY_LABELS_LOWER.has(dayPart.toLowerCase())) {
    return [...ALL_DAYS];
  }

  const segments = dayPart.split(',').map((s) => s.trim()).filter(Boolean);
  const out = new Set<string>();

  for (const segment of segments) {
    if (segment.includes('-')) {
      const [a, b] = segment.split(/\s*-\s*/).map((s) => s.trim());
      if (!a || !b) return null;
      const dayA = SHORT_TO_DAY[a.toLowerCase()];
      const dayB = SHORT_TO_DAY[b.toLowerCase()];
      if (!dayA || !dayB) return null;
      let ia = ALL_DAYS.indexOf(dayA);
      let ib = ALL_DAYS.indexOf(dayB);
      if (ia > ib) [ia, ib] = [ib, ia];
      for (let i = ia; i <= ib; i++) out.add(ALL_DAYS[i]);
    } else {
      const day = SHORT_TO_DAY[segment.toLowerCase()];
      if (!day) return null;
      out.add(day);
    }
  }

  return sortDaysWeekOrder([...out]);
}

function parseSchedule(value: string): ScheduleEntry[] {
  if (!value || value.trim() === '') return [];

  const entries: ScheduleEntry[] = [];
  const parts = value.split(';').map((s) => s.trim()).filter(Boolean);

  for (const part of parts) {
    const timeMatch = part.match(/(\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})/);
    if (!timeMatch || timeMatch.index === undefined) continue;

    const dayPart = part
      .slice(0, timeMatch.index)
      .replace(/[:\s]+$/u, '')
      .trim();

    const days = parseDayLabelString(dayPart);
    if (!days || days.length === 0) continue;

    entries.push({
      days,
      from: timeMatch[1],
      to: timeMatch[2],
    });
  }

  return entries;
}

function tFixed(lang: 'sr' | 'en'): (key: string) => string {
  return (key: string) => tr(key, lang);
}

export function WorkingHoursSelector({ value_sr, value_en, onChange }: WorkingHoursSelectorProps) {
  const { t } = useT();
  const [entries, setEntries] = useState<ScheduleEntry[]>(() => parseSchedule(value_sr));
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [showDayPicker, setShowDayPicker] = useState(false);
  const dayPickerRef = useRef<HTMLDivElement>(null);
  const initialValueSrRef = useRef(value_sr);

  // Sync from external Serbian value when parent resets (e.g. edit load)
  useEffect(() => {
    if (value_sr !== initialValueSrRef.current) {
      const parsed = parseSchedule(value_sr);
      if (parsed.length > 0 || value_sr === '') {
        setEntries(parsed);
      }
      initialValueSrRef.current = value_sr;
    }
  }, [value_sr]);

  // Serialize with fixed sr/en locales so DB columns stay language-correct regardless of UI language
  useEffect(() => {
    const serialized_sr = serializeSchedule(entries, tFixed('sr'));
    const serialized_en = serializeSchedule(entries, tFixed('en'));
    if (serialized_sr !== value_sr || serialized_en !== value_en) {
      onChange(serialized_sr, serialized_en);
      initialValueSrRef.current = serialized_sr;
    }
  }, [entries, value_sr, value_en, onChange]);

  // Close day picker on outside click
  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (dayPickerRef.current && !dayPickerRef.current.contains(e.target as Node)) {
        setShowDayPicker(false);
      }
    }
    if (showDayPicker) {
      document.addEventListener('mousedown', handleClick);
      return () => document.removeEventListener('mousedown', handleClick);
    }
  }, [showDayPicker]);

  const addEntry = () => {
    const newEntry: ScheduleEntry = { days: [...ALL_DAYS], from: '08:00', to: '22:00' };
    setEntries(prev => [...prev, newEntry]);
    setEditingIndex(entries.length);
  };

  const removeEntry = (idx: number) => {
    setEntries(prev => prev.filter((_, i) => i !== idx));
    if (editingIndex === idx) setEditingIndex(null);
  };

  const toggleDay = (idx: number, day: string) => {
    setEntries(prev => prev.map((entry, i) => {
      if (i !== idx) return entry;
      const has = entry.days.includes(day);
      const newDays = has ? entry.days.filter(d => d !== day) : [...entry.days, day];
      return { ...entry, days: newDays.length > 0 ? newDays : [day] }; // at least one day
    }));
  };

  const toggleEveryDay = (idx: number) => {
    setEntries(prev => prev.map((entry, i) => {
      if (i !== idx) return entry;
      const isAll = entry.days.length === 7;
      return { ...entry, days: isAll ? ['monday'] : [...ALL_DAYS] };
    }));
  };

  const updateTime = (idx: number, field: 'from' | 'to', val: string) => {
    setEntries(prev => prev.map((entry, i) => {
      if (i !== idx) return entry;
      return { ...entry, [field]: val };
    }));
  };

  const getDaysLabel = (entry: ScheduleEntry): string => {
    if (entry.days.length === 0) return t('chooseDays');
    return formatDayGroups(entry.days, t);
  };

  return (
    <div className="space-y-3">
      {/* Existing entries */}
      {entries.map((entry, idx) => {
        const isEditing = editingIndex === idx;
        
        return (
          <div
            key={idx}
            className="rounded-xl border transition-all"
            style={{
              borderColor: isEditing ? '#0E3DC5' : '#E5E9F0',
              background: isEditing ? '#F8FAFF' : '#FAFBFC',
              boxShadow: isEditing ? '0 0 0 3px rgba(14, 61, 197, 0.1)' : 'none'
            }}
          >
            {/* Summary row - always visible */}
            <div
              className="flex items-center gap-3 px-4 py-3 cursor-pointer"
              onClick={() => setEditingIndex(isEditing ? null : idx)}
            >
              <Clock className="w-4 h-4 shrink-0" style={{ color: '#0E3DC5' }} />
              <div className="flex-1 min-w-0">
                <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                  {getDaysLabel(entry)}
                </span>
                <span className="text-sm mx-2" style={{ color: '#9CA3AF' }}>|</span>
                <span className="text-sm font-semibold" style={{ color: '#0E3DC5' }}>
                  {entry.from} - {entry.to}
                </span>
              </div>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); removeEntry(idx); }}
                className="p-1 rounded-lg hover:bg-red-50 transition-colors border-0 bg-transparent cursor-pointer"
                title={t('removeSchedule')}
              >
                <X className="w-4 h-4 text-red-400 hover:text-red-600" />
              </button>
            </div>

            {/* Expanded editor */}
            {isEditing && (
              <div className="px-4 pb-4 pt-1 border-t" style={{ borderColor: '#E5E9F0' }}>
                {/* Day picker */}
                <div className="mb-4">
                  <p className="text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: '#6B7280' }}>
                    {t('chooseDays')}
                  </p>
                  
                  {/* Every day toggle */}
                  <button
                    type="button"
                    onClick={() => toggleEveryDay(idx)}
                    className="flex items-center gap-3 w-full py-2.5 px-3 rounded-lg mb-1 border-0 cursor-pointer transition-all"
                    style={{
                      background: entry.days.length === 7 ? 'rgba(14, 61, 197, 0.08)' : 'transparent',
                    }}
                  >
                    <div
                      className="w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 transition-all"
                      style={{
                        borderColor: entry.days.length === 7 ? '#0E3DC5' : '#D1D5DB',
                        background: entry.days.length === 7 ? '#0E3DC5' : 'white'
                      }}
                    >
                      {entry.days.length === 7 && <Check className="w-3 h-3 text-white" />}
                    </div>
                    <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                      {t('everyDay')}
                    </span>
                  </button>

                  {/* Individual days */}
                  <div className="space-y-0.5">
                    {ALL_DAYS.map(day => {
                      const isSelected = entry.days.includes(day);
                      return (
                        <button
                          key={day}
                          type="button"
                          onClick={() => toggleDay(idx, day)}
                          className="flex items-center gap-3 w-full py-2.5 px-3 rounded-lg border-0 cursor-pointer transition-all"
                          style={{
                            background: isSelected ? 'rgba(14, 61, 197, 0.05)' : 'transparent',
                          }}
                        >
                          <div
                            className="w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 transition-all"
                            style={{
                              borderColor: isSelected ? '#0E3DC5' : '#D1D5DB',
                              background: isSelected ? '#0E3DC5' : 'white'
                            }}
                          >
                            {isSelected && <Check className="w-3 h-3 text-white" />}
                          </div>
                          <span className="text-sm" style={{ color: isSelected ? 'var(--text-primary)' : '#6B7280', fontWeight: isSelected ? 500 : 400 }}>
                            {t(day as keyof typeof translations)}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Time pickers */}
                <div className="flex items-center gap-3">
                  <div className="flex-1">
                    <p className="text-xs font-semibold uppercase tracking-wide mb-1.5" style={{ color: '#6B7280' }}>
                      {t('timeFrom')}
                    </p>
                    <div className="relative">
                      <select
                        value={entry.from}
                        onChange={(e) => updateTime(idx, 'from', e.target.value)}
                        className="w-full px-3 py-2.5 rounded-lg border appearance-none cursor-pointer text-sm font-semibold"
                        style={{
                          borderColor: '#E5E9F0',
                          color: '#0E3DC5',
                          background: 'white',
                          paddingRight: '2rem'
                        }}
                      >
                        {TIME_OPTIONS.map(time => (
                          <option key={`from-${time}`} value={time}>{time}</option>
                        ))}
                      </select>
                      <ChevronDown className="w-4 h-4 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" style={{ color: '#9CA3AF' }} />
                    </div>
                  </div>

                  <span className="text-sm font-medium mt-5" style={{ color: '#9CA3AF' }}>—</span>

                  <div className="flex-1">
                    <p className="text-xs font-semibold uppercase tracking-wide mb-1.5" style={{ color: '#6B7280' }}>
                      {t('timeTo')}
                    </p>
                    <div className="relative">
                      <select
                        value={entry.to}
                        onChange={(e) => updateTime(idx, 'to', e.target.value)}
                        className="w-full px-3 py-2.5 rounded-lg border appearance-none cursor-pointer text-sm font-semibold"
                        style={{
                          borderColor: '#E5E9F0',
                          color: '#0E3DC5',
                          background: 'white',
                          paddingRight: '2rem'
                        }}
                      >
                        {TIME_OPTIONS.map(time => (
                          <option key={`to-${time}`} value={time}>{time}</option>
                        ))}
                      </select>
                      <ChevronDown className="w-4 h-4 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" style={{ color: '#9CA3AF' }} />
                    </div>
                  </div>
                </div>

                {/* Done button */}
                <button
                  type="button"
                  onClick={() => setEditingIndex(null)}
                  className="w-full mt-4 py-2.5 rounded-lg border-0 text-white text-sm font-semibold cursor-pointer transition-opacity hover:opacity-90"
                  style={{ background: 'linear-gradient(135deg, #60A5FA 0%, #0E3DC5 100%)' }}
                >
                  {t('done')}
                </button>
              </div>
            )}
          </div>
        );
      })}

      {/* Add button */}
      <button
        type="button"
        onClick={addEntry}
        className="flex items-center gap-2 w-full py-3 px-4 rounded-xl border-2 border-dashed cursor-pointer transition-all bg-transparent"
        style={{ borderColor: '#D1D5DB', color: '#6B7280' }}
        onMouseEnter={(e) => {
          e.currentTarget.style.borderColor = '#0E3DC5';
          e.currentTarget.style.color = '#0E3DC5';
          e.currentTarget.style.background = 'rgba(14, 61, 197, 0.03)';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.borderColor = '#D1D5DB';
          e.currentTarget.style.color = '#6B7280';
          e.currentTarget.style.background = 'transparent';
        }}
      >
        <Plus className="w-4 h-4" />
        <span className="text-sm font-medium">{t('addSchedule')}</span>
      </button>
    </div>
  );
}